language: node_js
node_js:
- '10'
before_deploy:
  - yarn build
deploy:
  provider: s3
  access_key_id: AKIAZVOMHKGPEAAPSAEU
  secret_access_key:
    secure: aTJ31PpQZjgYJ+lC+/ytz9DquXKMIOhTdML8PC0uHS+sOrB4G515c7ROBvhAEGBb1oqIDgM6OTR9yULAtwtR8HCWkd+TK0axa+rdSYyLh2mzXc9lwS5L/yNhj1Y4x0tUvUGH4ENc+FuUnJZVpd1bvlLu7OMVHDlH+h+hhz4hpJRX6gXx95NnBreFgdXRRaT/WqqoDmdF3TLOBAcIDQtBhBompvTJ/lpzX6Q3hd2yRjjTqJIv6HZXyZ6SvQjv7e2w8f5SGANNmpTOBt3+DFO2s2/0jMhfUIu2Hj0T6ELes3dHimg1e8J6kjVN+PKYkkOrbp6mIYE/li0ziYN9lt+n2fEZawFHceycWFe0rb+IOJDPoNj89JOuW2N8NunVU6+fnlkqM0PJnZfQyS25JD47ZQhtP3aYaiQRlcfSQsTstHY8ukglsKgf0T5GxDBEIPMxzJYN4ABl0oXQT6mFKUtCvu8A4G+XRcKZF9LB9g189gg8AF/cKEP53tgrWwed5CsLC2w6xHiOznqagkWJP7RDEu6KeQ92hAaYTulnyMXdfZAeXgonFTf2fjontuWvBeUHGcMZo57yg5sbHV8YSn14PUX9bheHqFvFgMVvOyfOzuhf0ZvDDveiAJdSWrjq8GKgerYDL683yplftRcxupJ2T1tB7J/r3CbgyzLjC3Yz1UQ=
  bucket: base-cms-management-components
  local-dir: dist
  acl: public_read
  on:
    tags: true
