version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.16.3
  entrypoint: ["node"]
  working_dir: /bmc
  volumes:
    - .:/bmc:cached
    - ./node_modules:/bmc/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    << : *node
    working_dir: /bmc
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  app:
    << : *node
    working_dir: /bmc
    entrypoint: ["/bmc/node_modules/.bin/vue-cli-service"]
    command: ["serve", "--port", "7290"]
    environment:
      <<: *env
    ports:
      - "7290:7290"

volumes:
  yarn-cache: {}
